
profile=high-quality
vo=gpu-next
gpu-api=vulkan
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=16
deband-grain=4
scale-antiring=0.5
dscale-antiring=0.5
cscale-antiring=0.5

sub-color='#F3CE32'
sub-font="Noto Sans Mono Medium"
sub-font-size=45
