Net/CursorBlinkTime 1000
Net/CursorBlink 1
Net/DoubleClickTime 250
Gdk/UnscaledDPI 108134
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout ":maximize,close"
Net/ThemeName ""
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gtk/CursorThemeSize 52
Gtk/CursorThemeName "Oxygen_Zion"
Net/SoundThemeName "ocean"
Net/IconThemeName "breeze-dark"
Gtk/FontName "SF Pro, Medium 11"

