# Fish Configuration File
## github.com/monikrab

##
## ENVIRONMENT VARIABLES
##

# Autocomplete color
set -U fish_color_autosuggestion 666

# Multithreaded tar
export XZ_OPT="-T0"

# Format manpages
set -x MANROFFOPT -c
set -x MANPAGER "sh -c 'col -bx | bat -l man -p'"

##
## ALIASES
##

# Replace ls with eza
alias ls='eza -al --color=always --group-directories-first --icons=always' # preferred listing

# Common use
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias wget='wget -c '
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias cl='clang'
alias ff='fastfetch'
alias clr='clear'

# Git aliases
alias push='git push -u origin main'
alias commit='git add . && git commit -m'

##
## FUNCTIONS
##

function fish_greeting
    #
end

# Fish command history
function history
    builtin history --show-time='%F %T '
end

##
## PROMPT
##

starship init fish | source

# Automatically generated by `declan init`
export DECLAN_CONFIG_PATH='/home/monikrab/nimas.json'
